### ISSUE TITLE
Document available commands in Listening mode

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#179]
Community conversation: https://community.particle.io/t/no-cores-found-cant-connect-to-spark-core/15278/11

Available here: https://github.com/spark/firmware/blob/dfa56424014eaf28a43ebeadbd11a80f646de7ae/system/src/system_setup.cpp#L78

**Comment by m-mcgowan** [comment]
I can describe the commands briefly here if someone wants to write up:
- 'i' : fetch the device ID. same as particle serial identify
- 'w': begin wifi configuration, similar to particle serial wifi
- 'm': display the MAC address (note does not work on unboxed photons unless they have firmware updated manually, e.g.via `particle update`)
- 's': display system information (again, not available unboxed photons until firmware update is applied.)
- 'v': display the system version, (since 0.4.4)

**Comment by kennethlimcp** [comment]
@cmsunu28 where does this possibly go?

**Comment by cmsunu28** [comment]
Maybe in guide/tools or support

I have actually never used this so it's hard for me to scope it. It seems like this should be a secondary method in the case that you can't connect with phone or cli in the typical way.

Do you want to outline it as a PR on the support page of docs as an article under "troubleshooting" and I'll take a look?

**Comment by kennethlimcp** [comment]
It's a feature of the Photon/Electron/Core so i am thinking where people would want to read about this.

Questions like:
- What is my system firmware?
- What is my mac address?
- Can i see more system info?

**Comment by cmsunu28** [comment]
I'm thinking we should add a FAQ to the support section of the docs. It could go there. What do you think?

**Comment by kennethlimcp** [comment]
Yeah that would be good. We should start a conversation since I had a building list of glossary of items that _should_ enter the docs but haven't found a good place to fit each of them with good flow when reading

**Comment by monkbroc** [comment]
Listen mode serial commands.

'i': Show device ID. For Core, outputs "Your core id is aaaaaaaaaaaaaaaaaaaaaaaa". For others it outputs "Your device id is aaaaaaaaaaaaaaaaaaaaaaaa"

'm': Displays MAC address. Outputs: "Your device MAC address is
6c:0b:84:c5:bd:3d" (2 lines)

'x': Exit listen mode

's': Detailed information about firmware versions. Outputs JSON.

'v': System version. Outputs "system firmware version: 0.6.0"

'f': Serial flash using the Y-modem protocol.

Since 0.6.0 also supports
'c': Get device claimed status. Outputs "Device claimed: yes" or "Device claimed: no"
'C': Accept claim code. Outputs "Enter 63-digit claim code: " and waits for new line.
