### ISSUE TITLE
Conflicting information on Android SDK availability?

### ISSUE THREAD

**Issue by embedded-creations** [particle-iot/docs#221]
https://docs.particle.io/guide/how-to-build-a-product/mobile-app/ says
"Particle Android SDKs: Cloud SDK (coming soon) and Device Setup library (coming soon)" at the top, but has links to GitHub repos at the bottom.  Are these pre-release and not recommended, or is the info at the top out of date?

**Comment by jensck** [comment]
Thanks for the heads-up @embedded-creations !  The Android SDKs are live; those links just needed to be updated.

As for the status of the SDKs, they're stable and usable -- that very same code is what powers the production Particle setup app right now.  Technically I've still labelled them "beta" though, because there are a few remaining features where they currently lag behind iOS (e.g.: alternate authorization options, event subscription), and because the API aren't guaranteed to be completely frozen yet (though any changes should be minor).

Once the Cloud SDK and Device Setup lib hit 1.0, the beta label will be removed, and the intent is to _never_ break API without a major version bump, e.g.: 2.0.
