### ISSUE TITLE
Sub-headings missing in firmware

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#28]
Seems like the sub-headings for each category is missing.

Eg. `SPI` and `System modes`

See: http://docs.particle.io/photon/firmware/#communication

They all all listed under one heading of `communication`

**Comment by zsup** [comment]
I think this might be just a styling issue? the subheadings in the left-hand column definitely aren't as clear now with some of the styling changes (ping @jme783)

**Comment by wgbartley** [comment]
If you change the `font-weight` from `normal` to `bold` in [src/stylesheets/menu.less#L127](https://github.com/spark/docs/blob/48593f8eee00aa65063d546220a84ff02f740993/src/stylesheets/menu.less#L127), it should be good enough without going over a whole styling change for all the menu levels.

![screen shot 2015-05-21 at 12 06 43 am](https://cloud.githubusercontent.com/assets/271242/7741487/61e59cc0-ff4d-11e4-9ce8-dcf46d8ff4ca.png)
_The screenshot may look a little overblown from my laptop, but I assure you that it looks better in the browser than the screenshot suggests._

_PS - I'm kind of being lazy by responding to this issue rather than cloning the repo, making the change, pushing the change, and then sending a pull request for a really tiny suggestion._

**Comment by kennethlimcp** [comment]
@wgbartley looks great but the previous docs had an indent for all the sub-category items for it to be seen easily. Wished i had a fix but that's not my area of expertise!

**Comment by moors7** [comment]
How does this look? Should be an easy fix :)
![image](https://cloud.githubusercontent.com/assets/6599791/7785886/84ee9a16-01a8-11e5-8c95-faa95c31d2e8.png)

**Comment by kennethlimcp** [comment]
@moors7 , PR please?! :)

**Comment by moors7** [comment]
With me not having a lot of experience with GitHub, and the fear that I'll break something, I think I prefer Garret's method :sweat_smile: 

If you go to [/src/stylesheets/content.less#L474](https://github.com/spark/docs/blob/48593f8eee00aa65063d546220a84ff02f740993/src/stylesheets/content.less#L474)
And replace this:

``` css
.menubar .level-2, .menubar .level-3 {
  padding-left: 10px;
}
```

by this:

``` css
.menubar .level-2 {
  padding-left: 10px;
}

.menubar .level-3 {
  padding-left: 20px;
}
```

then it should be fixed.

Let me know if you guys still prefer a pull request, and I'll try and figure it out :)

**Comment by kennethlimcp** [comment]
@moors7, i will pull the repo, add in your change to test before pushing to the repo :)
