### ISSUE TITLE
Electron Pinout PDF Clarification

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#310]
From the community: http://community.particle.io/t/electron-i2c-bus/20941/5

In the docs: https://docs.particle.io/datasheets/electron-datasheet/#pinout-diagram, the PDF has **SCL/SDA** wrongly labeled
https://docs.particle.io/assets/images/electron/illustrations/electron_pinout.pdf

**Comment by mohitbhoite** [comment]
@kennethlimcp can you elaborate on the error? Currently the PDF says:
D1 - SCL
D0 - SDA
C5 - SCL
C4 - SDA
which is correct

**Comment by kennethlimcp** [comment]
@mohitbhoite , not sure which PDF you are referring to but the latest one i get from `master` shows this:

<img width="307" alt="screen shot 2016-03-12 at 08 20 57" src="https://cloud.githubusercontent.com/assets/6760914/13719067/9c94d378-e82b-11e5-8064-072d98778adb.png">

They are offset by one pin...

AH...i think i know why now.... It's hard to tell whether to read the top or bottom label for that particular pin.... We are looking at D1 for SDA

**Comment by technobly** [comment]
Confirmed the PDF is correct (and I'm still unclear what the PDF was being compared to that was "correctly" labeled as stated in the community post). It is impossible to know when looking only at these pins if the pin is above or below the label. You can look at B0 and C0 for a reference, and also D6 and D7 should be very clear.   From these keys (and the labels on the sides of the headers) it should be fairly clear how to read the pins.  That said, I would like to suggest an additional row of pin labels in the PDF pinout right next to the the pins on the pinout diagram.  That'd be helpful, yeah?

![incorrect_electron_pdf_ _issue__310_ _spark_docs](https://cloud.githubusercontent.com/assets/2249224/13720475/51049b98-e7cf-11e5-9c7e-3bf8a121456a.png)

For reference:
![screen shot 2016-03-11 at 9 12 05 pm](https://cloud.githubusercontent.com/assets/2249224/13720459/c8a7d530-e7ce-11e5-8728-57e48ed48849.png)

**Comment by ScruffR** [comment]
One thing I'm not sure about is why there are **two** set of pins when there is only **one** I2C bus and I can't find any indication in the docs to explicitly select which set (as is done for SPI via [`SPI1` or `SPI2` and documented](https://docs.particle.io/reference/firmware/electron/#spi)) - sure the reason is the same as for SPI3 if one set is occupied for other use (e.g. CAN2 for D1) you don't want to loose I2C and move to C4/C5. But how? 
If they are wired parallel internally, would external circuitry on the "other" set not interfere?

Might be a dumb question, but I sometimes I'm a bit slow :blush:

BTW: The [reference docs](https://docs.particle.io/reference/firmware/electron/#wire-i2c-) only mention D0/D1 and not at all C4/C5 - maybe this is what the OP meant with the "correct info".
He might think the the tags next to C4/C5 are a copy-past artefact rather than getting confused by pin lables above/below.

**Comment by kennethlimcp** [comment]
@technobly it's probably from this diagram - https://docs.particle.io/reference/firmware/electron/#wire-i2c-

**Comment by technobly** [comment]
@ScruffR there is an alternate location on the Electron, just in case you need it.  Hmm, I see the documentation is missing!! GAH.  Essentially replace all of your `Wire` calls with `Wire1`.  I'll update the docs, and get rid of that Core image for Electron docs... thanks @kennethlimcp

**Comment by technobly** [comment]
@ScruffR updated I2C docs: https://github.com/spark/docs/commit/3d87c8e0862c998a0093428f8c67de3b67c16bb9

**Comment by leo3linbeck** [comment]
So, a quick follow-on question:

Is it OK to use both Wire and Wire1 on the Electron? I have two sensors hardwired with the same I2C address (ugh) but I'm hoping that I can use one on Wire and one on Wire1. Does that make sense? Is that doable?

Cheers,
L3

**Comment by ScruffR** [comment]
@technobly, now it makes sense :+1: 
@leo3linbeck, I'd say not since there is actually only **_one**_ I2C interface which can be mapped to **either** the one **or** the other sets of pins.

**Comment by leo3linbeck** [comment]
@ScruffR,

I was afraid you'd say that.... I'm going to experiment and if I find anything interesting, I'll report back. Cheers,

L3

**Comment by ScruffR** [comment]
What sensors are you using?
Could you open a thread on community.particle.io to continue there?

**Comment by leo3linbeck** [comment]
OK, I'm getting confused, so I'm returning to the font of all Particle wisdom.

Here's my setup:

Two TCS34725 color sensors: SensorA and SensorB. They have identical I2C addresses.
I've connected SensorA to D0 and D1, and SensorB to C4 and C5 on an Electron.

I don't need to use SensorA and SensorB at the same time.

Seems like I should be able to call Wire.begin() on initialize SensorA, take some readings, call Wire.end() to release the pins, and then call Wire1.begin() to initialize SensorB, take some readings, call Wire1.end() to release the pins, etc etc etc.

But when I actually try to do this, it doesn't work. It appears both sensors stay active, and it actually takes the higher of the two sensors, which is kinda weird but that's what it's doing.

Seems like because SensorA and SensorB are on separate pins, I should be able to flip back and forth between the two interfaces. But maybe even though the pins are released, the sensor on the released pins is still connected.

Anyway, I hope this makes sense and that there is some way to switch back and forth between I2C pin pairs. Any help would be greatly appreciated.

Cheers,
L3

**Comment by leo3linbeck** [comment]
Oh, good idea. I'll move over to community.particle.io. Thx, L3

**Comment by mohitbhoite** [comment]
[Updated!](https://github.com/spark/docs/commit/64c5c865bfa35503985331e5eea860a1641e0ed1)
