### ISSUE TITLE
<blockquote> (`> ` markdown) hidden in 2 column view

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#374]
See: http://localhost:8080/reference/firmware/photon/#selectantenna-

You will notice that the text below doesn't show up... Drag the right end of the browser inwards until the code block is inline with the text portion and you will see it appear.

```
> Note that the antenna selection is remembered even after power off or when entering safe mode.
This is to allow your device to be configured once and then continue to function with the
selected antenna when applications are flashed that don't specify which antenna to use.
```

**Comment by ScruffR** [comment]
Another note missing because of this was my update here (removed `>` now, in order to make it appear)
![screenshot 36](https://cloud.githubusercontent.com/assets/6604878/14766404/a0139d00-0a08-11e6-9246-fabed86a7740.png)
vs.
![screenshot 35](https://cloud.githubusercontent.com/assets/6604878/14766405/ad0f8a3c-0a08-11e6-9764-bb849fc80014.png)

**Comment by monkbroc** [comment]
Good catch folks. I'll fix the CSS for the `<blockquote>` element on the docs site.
