### ISSUE TITLE
Power Shield

### ISSUE THREAD

**Issue by Jack706** [particle-iot/docs#381]
I am new to the Photon. I have 2 Photons and one power shield. two questions
1. do I solder the headers that came with the power shield to the power shield?
2. If I solder the header pins to the power shield do I just plus a Photon into the power shield?

I don't understand how to get power from the power shield to the Photon.

Thanks
Jack Burn

**Comment by kennethlimcp** [comment]
1.) I believe you have to do so since they come unpopulated

2.) You will need to either attach the Lipo battery or plug the USB cable to the power shield in order to power up the Photon.

You can think of it as using the Lipo battery to power up the Photon and the usb cable to the power shield is to charge the Lipo (and at the same time deliver power to the Photon)

Hope this helps! If you have more issues, you can post it here: http://community.particle.io/c/hardware
