### ISSUE TITLE
Improve searchability of app hash

### ISSUE THREAD

**Issue by towynlin** [particle-iot/docs#406]
Searching for "app hash" or "unique id" should show app hash as search result:
https://docs.particle.io/reference/api/#app-hash

**Comment by monkbroc** [comment]
This section is too deeply nested (Special Events -> Special Device Events -> app-hash) so it won't show up in the current search results. Special Device Events do show up when searching for app hash.

So either we un-nest app-hash, or we revisit the docs search in a later sprint. I think we should do the latter since now the search is weird with Photon/Core/Electron results showing up for firmware (for example search for PWM).
