### ISSUE TITLE
Fix OTA update notes [ System.updatesPending() ]

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#452]
https://docs.particle.io/reference/firmware/electron/#system-updatespending-

Either we remove it or fix the TODO note.

Related: http://community.particle.io/t/electron-0-5-2-system-updatespending/24950

The docs doesnt spell out exactly how `System.updatesPending()` works and the scenarios it wont.

**Comment by technobly** [comment]
You can check with system events when an update is pending if updates are disabled. I don't think the `System.updatesPending()` API works like some think it should. The last time I tried to use it I did not get it to fire unless updates were enabled.  It may just be useful for multi-threaded mode when user code continues to execute https://docs.particle.io/reference/firmware/electron/#system-updatespending-

@m-mcgowan would you please comment on this.  If it is suppose to work when updates are disabled, we can verify it doesn't and file a bug report.  Otherwise we just need to clarify the Docs with how it should be used.

**Comment by technobly** [comment]
### Related issues:

https://github.com/spark/docs/issues/354
https://github.com/spark/docs/issues/318
