### ISSUE TITLE
"Troubleshooting" section missing in navigation sidebar of docs root page

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/docs#46]
I can navigate to http://docs.particle.io/photon/troubleshooting/ and http://docs.particle.io/core/troubleshooting/ direct, but when going via the landing page http://docs.spark.io/ the link is nowhere to be found in the nav bar.

Also the nav bar is inconsistent between the troubleshooting pages and the root oage (and others).

![troubleshooting](https://cloud.githubusercontent.com/assets/6604878/7830159/1cc4a954-044a-11e5-83c1-b7ff6cc2d484.png)

**Comment by kennethlimcp** [comment]
@ScruffR i don't think the **Troubleshooting** section is available anymore.

I'm purely guessing that the old files are still sitting inside. https://github.com/spark/docs/blob/master/.travis.yml#L12

@joegoggins or @jme783 can you guys take a look into this?

**Comment by ScruffR** [comment]
It would be a pitty if this page (or pages now) was droppen, since it was quite handy to refere people to, to tick off a bunch of possible standard causes, without having to elaborate over and over again
And the pages are still there, as you can see.

If it's for the sake of _not_ mentioning the word "trouble" on the first page, then it would at least be good to have it as a sub-section in "Connecting your Device" and wherever else fitting ;-)

**Comment by kennethlimcp** [comment]
Not sure what's wrong but it was removed here: https://github.com/spark/docs/commit/1da1b32f4b2d795f2e54a923ad9ffe1ac51a28e3

These changes were made during the rebranding and I wasn't aware so let's wait for the team to tell us more about this.

**Comment by joegoggins** [comment]
Good question guys, I'm not sure if that was intentional or not, looks like not, because the [content is still there](http://docs.particle.io/core/troubleshooting/), but it's not linked to.

@jme783 was there a broader goal in removing the Troubleshooting section, like shooting to move it into support.particle.io or something or does it simply need to get re-added to the navigation again?

**Comment by zsup** [comment]
I believe this was removed because the content was moved over to support.particle.io - @kmmonk, is that right? If so, we should add a better link to that content from the docs so that people can find their way over there.

**Comment by kmmonk** [comment]
That's correct @zsup. Everything got ported over to support.particle.io in the troubleshooting section so instead of having duplicate pages, troubleshooting and support, everything is on the support page now. I am constantly adding more articles (or at least trying to) to the support page, so eventually, I'd like it to be much more robust than the troubleshooting page was.

**Comment by kennethlimcp** [comment]
@joegoggins so someone needs to clean up the S3 bucket!

**Comment by joegoggins** [comment]
I just manually deleted the troubleshooting pages from the S3 bucket. But I believe the underlying reason why it's not getting cleaned up automatically is because we set `skip_cleanup: true` in our [Travis-CI yml](https://github.com/spark/docs/blob/master/.travis.yml#L12) when it should be false. More info about this [setting here](http://docs.travis-ci.com/user/deployment/s3/)

Before I make this change, I want to verify that this is okay with @zsup , who initially set this integration up. Zach--are there are any assets in this docs.particle.io bucket that are not managed by the travis-ci integration? If no, then changing this flag is the right solution.  Let me know and I can flip switches.

**Comment by zsup** [comment]
Nothing in there that isn't managed by travis. Thanks @joegoggins et al!

**Comment by kennethlimcp** [comment]
@joegoggins i did an accidental push to master instead of creating a new branch but reverted it.

I think they might be other settings for S3 bucket clean up which has to be looked into.

**Comment by joegoggins** [comment]
Boo, re-opening this issue.

`skip_cleanup: false` doesn't work as expected. [Travis-CI build output](https://travis-ci.org/spark/docs/builds/64992952) says this:

```
Deploying application
Already up-to-date!
# HEAD detached at cc35cd1
nothing to commit, working directory clean
Dropped refs/stash@{0} (f3f22e45320febc4bbe85025fa760d3316dc5929)
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider/s3.rb:37:in `chdir': No such file or directory - build (Errno::ENOENT)
  from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider/s3.rb:37:in `push_app'
  from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider.rb:134:in `block in deploy'
  from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/cli.rb:41:in `fold'
  from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider.rb:134:in `deploy'
  from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider/s3.rb:59:in `deploy'
  from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/cli.rb:32:in `run'
  from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/cli.rb:7:in `run'
  from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/bin/dpl:5:in `<top (required)>'
  from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
  from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

Also, adding a .gitkeep file to the `build` dir also does not solve the "no build dir" error error either, in that case we get a silent failure in which [travis-ci claims the build succeeded](https://travis-ci.org/spark/docs/builds/64996443), but it does not succeed in uploading to S3 with an error like this:

```
Deploying application
Removing build/.gitkeep
# HEAD detached at 8ddce75
# Changes not staged for commit:
#   (use "git add/rm <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#   deleted:    build/.gitkeep
#
no changes added to commit (use "git add" and/or "git commit -a")
Dropped refs/stash@{0} (d34213e02b0d207ce99cf285a1083157230b51ee)
Done. Your build exited with 0.
```

**Comment by kennethlimcp** [comment]
Closing this as `troubleshooting` is now under **support**
