### ISSUE TITLE
Self-scrolling/persistent nav-bar

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#57]
As the **firmware** page grows, looking at content way below requires a user to scroll back _wayyyyy_ up in order to navigate through other sections.

Would be great if the nav-bar if the left stays while content on the right scrolls!

@wgbartley

**Comment by moors7** [comment]
I think it would be pretty neat if the black subheading would be collapsible. That way it'll only show you the bits your interested in, without having to scroll through it all.
If that's possible, it'd be great if it automatically "activated" the heading you're at on the page. Meaning that if you scroll to another part of the docs, the menu goes along with that.
Making the menus collapsible would also benefit mobile users since you currently have to go through the complete menu to get to your content. Making an off-canvas menu for mobile users would be even nicer, since you then wouldn't have to scroll all the way back up to get to the menu.
Just some ideas if the front-page team has to much time on their hands ;)

**Comment by kennethlimcp** [comment]
:+1: - It's just crazy how much i try to check the docs back and forth only to scroll infinitely up and down!

**Comment by kennethlimcp** [comment]
Seems like that's the current behavior so closing this.
