### ISSUE TITLE
Adjust docs.spark.io -> docs.particle.io redirect

### ISSUE THREAD

**Issue by joegoggins** [particle-iot/docs#61]
A fellow reported that docs.spark.io redirects weren't working correctly here: https://community.particle.io/t/spark-io-to-particle-io-redirection-breaks-core-docs-links/
It's true :)

Please change redirect logic so `http://docs.spark.io/*` redirects to `http://docs.particle.io/photon/*` where `*` is anything.

**Comment by kennethlimcp** [comment]
@joegoggins thanks for the input. i asked this before but did not get a reply. The best thing is to redirect to the actual core/photon selection though.

**Comment by moors7** [comment]
Assuming most, if not all, of those links are from the pre-photon era, wouldn't it be better to redirect them to the Core pages?

**Comment by joegoggins** [comment]
@kennethlimcp , this core vs photon structure didn't exist before, so it's impossible for a simple http redirector script to know where to redirect, we have to pick one.

@moors7 , I hear you, that was my initial thinking too. @cmsunu28 was thinking that longer term, for links discovered in community posts and all over the internet, we'd be better off redirecting to the Photon docs because these docs are very similar to core docs now and will be enhanced as things change going forward, so will provide more up to date info.  After considering that logic, I was persuaded.

**Comment by kennethlimcp** [comment]
Yeah but it's poor UX when you get redirected to a photon page when you browse let's say core/electron

**Comment by moors7** [comment]
I was under the assumption the new docs came at the same time the Photon docs came into existence. Therefor, all links prior to that have to be Core-related. If so, then they will be routed correctly when we send 'em over to the Core pages. The same is true for any links on the Web. If you're linking people to docs where it explains the single-threaded Core, they shouldn't end up at a multi-threaded Photon(?)
Any new links will likely(/certainly) use the correct Particle adress, and therefor not require rerouting.

@kennethlimcp, the electron shouldn't be an issue, since those docs are yet to be created/added, and will therefor already use the new address.

**Comment by kennethlimcp** [comment]
Ok i think the way to do it is `../file_name#rel-link`. 

@joegoggins, i'm not sure who is managing the redirect but i don't see anything here in the repo causing the issue.... 

Who ever making the update should redirect `http://docs.spark.io/*` to `http://docs.particle.io`

**Comment by joegoggins** [comment]
Instead of statically determining what page a user should be redirected to, the first step we're going to take to resolve this is by creating a friendly 404 "page not found" page. From there, and once we have docs search in place, we will likely introduce further language + logic that helps a user find the desired page. It might prompt the user to do a search. It might prompt the user to choose "Core", "Photon". Will re-assess once the friendly 404 is in place.

**Comment by kennethlimcp** [comment]
Closing with the introduction of metalsmith docs
