### ISSUE TITLE
in getting-started, it's easy to get lost when you just want the setup page link

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/docs#671]
for those of us who are experienced setting up a device, or who don't want to read about what's in the box, we need a clear "start setting up my device" link that goes straight to setup.particle.io

for example, something like:

<img width="1430" alt="screen shot 2017-08-08 at 9 17 24 am" src="https://user-images.githubusercontent.com/833793/29076256-9ab05260-7c1a-11e7-9bab-05e11208cdd7.png">

**Comment by BookSwapSteve** [comment]
Personally (as an experienced Photon/Electron user) I'd prefer if clicking the Electron on the /Start page took me directly to the Start.Particle.io Electron setup, with a big [Help]/[Getting Started Guide] button for those who are unsure. A page telling me what the battery is and what pins do is of little interest.

I should add, my Electrons have the "Visit particle.io/start" blue slip with them, you may have changed this since I purchased mine (some from the Kickstarter) so it may be a little less confusing for newer customers.
