### ISSUE TITLE
Add `__SPISettings()` to docs _Since 0.6.2_ without `#include "arduino.h"` requirement

### ISSUE THREAD

**Issue by technobly** [particle-iot/docs#681]
See issue posted in https://github.com/spark/firmware/issues/1381

Add note to https://docs.particle.io/reference/firmware/photon/#spisettings

**Note:** Either `SPISettings()` or `__SPISettings()` may be used **with** `#include "Arduino.h"`
`__SPISettings()` should be used **without** `#include "Arduino.h"`

Change examples to use `__SPISettings()` to avoid confusion.

**Comment by ScruffR** [comment]
That might be a way to go (as long `__SPISettings()` will get a long life ;-) )

**Comment by ScruffR** [comment]
After some more thinking, the second part might be a bit confusing.

How about this?
> **Note:** Either `SPISettings()` or `__SPISettings()` may be used **with** `#include "Arduino.h"`.
> **Without** explicit `#include "Arduino.h"` the only available option is `__SPISettings()`.
> Platform portable code should include `Arduino.h` and use the default version `SPISettings()`.

**Comment by technobly** [comment]
@ScruffR I'm ok with adding "explicit", makes sense.  When you say "Platform portable" do you mean Arduino platform?  I was specifically trying to avoid talking too much here in the SPI help about Arduino, since that really requires it's own section somewhere else.  In that section we'd talk about what compatibility you get with and without explicitly including the Arduino.h header.  So in that case, I'd like to just state what form of SPISettings should be used with and without Arduino.h in the note for now, without any recommendation on why either way is better.  Also our documented API's and examples should work without needing to include Arduino.h and should be written such that the default way is the Particle API.

So I would change it to this:

>**Note:** `__SPISettings()` is the **default** form that should be used with the **Particle platform**.
>**When explicitly using** `#include "Arduino.h"`, these two forms are available: `SPISettings()` (_Since 0.6.1_) or `__SPISettings()` (_Since 0.6.2_).

Sound good?

**Comment by ScruffR** [comment]
That's stating it perfectly clear 👍 
And a dedicated Arduino compatibility section will be welcome too.

**Comment by m-mcgowan** [comment]
I don't feel `__SPISettings()` should be documented. Symbols beginning with underscores are meant to be internal and are not part of our public API. 

`SPISettings` was a new addition to the Arduino-compatible API, that should have been enabled always via an inclusion of `Arduino.h`, but this slipped through the net.  The requirement to include the header is necessary to avoid breaking libraries that define their own `SPISettings` symbol, since this was not present until 0.6.1 (iirc)

**Comment by ScruffR** [comment]
On the other hand introducing libraries v2 along with auto-migration did break several libraries too, but noone pulled that back.
I'm pretty sure the number of broken libs due to v2 were greater than the few being broken by making `SPISettings()` omnipresent again.

The few libs affected can be fixed easily.

After all general "Arduino compatibility" - even with *only* `Particle.h` included - was the holy grail for other topics (e.g. and as argument *against* a superior implementation of `serialEvent()` 😉 )

**Comment by m-mcgowan** [comment]
SPISettings and other new symbols are part of our versioned Arduino API, which encompasses all changes since the original Particle API.  The `ARDUINO` symbol defines the version (presently 180) which library vendors can use to determine if they need to conditionally define a symbol or not. 

No libraries were intentionally broken with the v2 effort, and we went to a lot of effort to reduce the impact of the change.  Re-introducing SPISettings, after removing it, after adding it would just create more confusion.  I would prefer to go with a cohesive strategy that all new Arduino symbols require Arduino.h to be included.

**Comment by ScruffR** [comment]
Then why are `SPI.beginTransaction()` and `SPI.endTransaction()` not confined to the Arduino world when the former of the two requires an otherwise inaccessible structure?

I sense a degree of inconsistency/incoherence here just the same.

BTW, I didn't imply v2 did break things intentionally, neither would public `SPISettings()` break things intentionally, but accepting the minor impact on a few (any estimate of numbers?) libraries that did something that wasn't "meant to be done" for the bigger goal to have a long missed feature in the Particle realm too.

I think this needs a broader strategic discussion - @towynlin?

**Comment by m-mcgowan** [comment]
Allowing Libraries and Applications to define their own versions Arduino symbols that may be added in future firmware releases is meant to be done and very much a supported use case - it is one of the key motivators behind putting new symbols behind the include of "Arduino.h", and using the `ARDUINO` symbol as a version indicator so that library/application developers can know which Arduino symbols will be defined in a given firmware release. 

I've made a draft of a change to the docs that I hope clarifies the intent. I will be looking to rework it to make it clearer, and welcome any input there. 

Looking at it now, one possible reason for including `SPI.beginTransaction()` et al is because there is no possibility of a name clash, since it exists within our own `SPI` namespace.  But I support your point that there is little reason to including it if it cant be used without `SPISettings`.  I don't recall the reasoning at the time, and this could have been an oversight.

**Comment by ScruffR** [comment]
> Allowing Libraries and Applications to define their own versions Arduino symbols that may be added in future firmware releases is meant to be done and very much a supported use case - it is one of the key motivators behind putting new symbols behind the include of "Arduino.h", and using the ARDUINO symbol as a version indicator

In this regard people should also be advised to use a similar pattern as in the Arduino world
```
#if (ARDUINO < 0100) 
// use old version
#else 
// new version
#endif
```
for each yet-to-be implemented Arduino feature in the Particle world the user wants to implement on his own.
But AFAIK the `SYSTEM_VERSION` variable - which should be used for that - isn't documented clearly enough.
